language: csharp
solution: ./source/slnMeetingRoomReservation.sln
mono:
- latest
script: make build
install:
- sudo apt-get install nunit-console
#- nuget restore ./source/slnMeetingRoomReservation.sln
script:
  - xbuild ./source/slnMeetingRoomReservation.sln
  #- nunit-console ./src/MeetingRoomReservation.Data.SqlServer.IntergationTests/bin/Debug/MeetingRoomReservation.Data.SqlServer.IntergationTests.dll